var express = require('express');
var router = express.Router();
const clienteController = require('../controllers').clienteController;
const { requireAuthJWT } = require('../middlewares/authJwtMiddleware');
router.get('/', requireAuthJWT, clienteController.list);
router.get('/productos-por-cliente', requireAuthJWT, clienteController.productosPorCliente);
router.get('/productos-por-cliente/vendedor/:idVendedor', requireAuthJWT, clienteController.productosPorClientePorVendedor);
router.get('/debug-productos-por-cliente/vendedor/:idVendedor', requireAuthJWT, clienteController.debugProductosPorClientePorVendedor);
router.get('/debug-ventas-por-vendedor/:idVendedor', requireAuthJWT, clienteController.debugVentasPorVendedor);
router.get('/:id', requireAuthJWT, clienteController.getById);
router.post('/', requireAuthJWT, clienteController.add);
module.exports = router;