var express = require("express");
var router = express.Router();
const cumplimientoMesController = require("../controllers").cumplimientoMesController;
router.get("/cumplimiento", cumplimientoMesController.getCumplimientoCuotaMes);
router.get("/cumplimiento/:codigo", cumplimientoMesController.getCumplimientoPorCodigo);
router.get("/cumplimiento/linea/:linea", cumplimientoMesController.getCumplimientoPorLinea);
router.get("/cumplimiento/vendedor/:codigo/linea/:linea", cumplimientoMesController.getCumplimientoVendedorYLinea);
router.get("/cumplimiento/vendedor/:codigo/lineas", cumplimientoMesController.getCumplimientoVendedorDetalleLineas);
router.get("/cumplimiento/vendedor/:codigo/ciudades", cumplimientoMesController.getCumplimientoVendedorPorCiudad);
module.exports = router;