const { DataTypes } = require("sequelize");
module.exports = (sequelize) => {
  const attributes = {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: null,
      comment: null,
      primaryKey: true,
      field: "id",
      autoIncrement: true,
    },
    venta_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "venta_id",
      autoIncrement: false,
      references: {
        key: "id",
        model: "ventas_model",
      },
    },
    producto_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "producto_id",
      autoIncrement: false,
      references: {
        key: "id",
        model: "productos_model",
      },
    },
    unidad_medida_id: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "unidad_medida_id",
      autoIncrement: false,
      references: {
        key: "id",
        model: "unidades_medida_model",
      },
    },
    cantidad_emp: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "cantidad_emp",
      autoIncrement: false,
    },
    cantidad: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "cantidad",
      autoIncrement: false,
    },
    costo_promedio_total: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "costo_promedio_total",
      autoIncrement: false,
    },
    valor_bruto: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "valor_bruto",
      autoIncrement: false,
    },
    valor_descuentos: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "valor_descuentos",
      autoIncrement: false,
    },
    valor_subtotal: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "valor_subtotal",
      autoIncrement: false,
    },
    valor_impuestos: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "valor_impuestos",
      autoIncrement: false,
    },
    valor_neto: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "valor_neto",
      autoIncrement: false,
    },
    margen_promedio: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "margen_promedio",
      autoIncrement: false,
    },
    impuesto_afecta_margen: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "impuesto_afecta_margen",
      autoIncrement: false,
    },
    factor_um_emp: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "factor_um_emp",
      autoIncrement: false,
    },
    factor_um_orden: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "factor_um_orden",
      autoIncrement: false,
    },
    peso_kilo: {
      type: DataTypes.DOUBLE,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "peso_kilo",
      autoIncrement: false,
    },
  };
  const options = {
    tableName: "ventas_detalle",
    comment: "",
    indexes: [
      {
        name: "idx_detalle_producto",
        unique: false,
        fields: ["producto_id"],
      },
      {
        name: "idx_detalle_venta",
        unique: false,
        fields: ["venta_id"],
      },
    ],
    timestamps: false,
    underscored: true,
    freezeTableName: true,
    schema: "public",
  };
  const VentasDetalleModel = sequelize.define(
    "ventas_detalle_model",
    attributes,
    options,
  );
  return VentasDetalleModel;
};
